### ISSUE TITLE
Reservation Service

### ISSUE THREAD

**Issue by Girin7716** [KNU-CSE-APP/Server#31]
## 기능 구현

- [x] User 강의실 안 특정 좌석 정보 찾기
- [x] 강의실 안 예약 가능한 모든 좌석 찾기
- [x] 강의실 안 예약 불가능한 모든 좌석 찾기
- [x] 예약 가능한 모든 좌석 찾기
- [x] 멤버가 예약하면 그에 따른 로직 구현
- [x] 관리자 예약 관리
- [x] 6시간 후 자동 db 삭제(자동 자리 반납)
- [x] 예약 동시성 관리
